from alembic import op
from sqlalchemy import text

revision = "20261001_auth_family_consent"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE TABLE "user" (\n\tid UUID NOT NULL, \n\tglobal_status VARCHAR(16) DEFAULT \'ACTIVE\' NOT NULL, \n\tdisplay_name VARCHAR(120) NOT NULL, \n\tphone_ciphertext TEXT, \n\tphone_hash CHAR(64), \n\tphone_last4 CHAR(4), \n\taccessibility_settings JSONB DEFAULT \'{}\' NOT NULL, \n\ttimezone VARCHAR(64) DEFAULT \'Asia/Shanghai\' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_user_status CHECK (global_status IN (\'ACTIVE\',\'SUSPENDED\',\'DELETED\')), \n\tCONSTRAINT ck_user_name CHECK (length(display_name) > 0), \n\tCONSTRAINT ck_user_settings CHECK (jsonb_typeof(accessibility_settings) = \'object\'), \n\tUNIQUE (phone_hash)\n)')
    op.execute('CREATE TABLE device_binding (\n\tid UUID NOT NULL, \n\tdevice_id_hash CHAR(64) NOT NULL, \n\towner_user_id UUID NOT NULL, \n\tdevice_type VARCHAR(32) NOT NULL, \n\tapp_version VARCHAR(64) NOT NULL, \n\tos_version VARCHAR(64) NOT NULL, \n\tkiosk_status VARCHAR(24) DEFAULT \'UNKNOWN\' NOT NULL, \n\twakeword_status VARCHAR(24) DEFAULT \'UNKNOWN\' NOT NULL, \n\tble_status VARCHAR(24) DEFAULT \'DISCONNECTED\' NOT NULL, \n\tcamera_permission VARCHAR(16) DEFAULT \'UNKNOWN\' NOT NULL, \n\tphone_permission VARCHAR(16) DEFAULT \'UNKNOWN\' NOT NULL, \n\tcapabilities JSONB DEFAULT \'{}\' NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'ACTIVE\' NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE, \n\tlast_state_change_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_device_type CHECK (device_type IN (\'ANDROID_TABLET\',\'ANDROID_PHONE\',\'OTHER\')), \n\tCONSTRAINT ck_device_kiosk CHECK (kiosk_status IN (\'UNKNOWN\',\'ACTIVE\',\'CONFIG_ERROR\',\'DISABLED\')), \n\tCONSTRAINT ck_device_wakeword CHECK (wakeword_status IN (\'UNKNOWN\',\'READY\',\'DISABLED\',\'ERROR\')), \n\tCONSTRAINT ck_device_ble CHECK (ble_status IN (\'DISCONNECTED\',\'CONNECTING\',\'CONNECTED\',\'LOW_BATTERY\',\'ERROR\')), \n\tCONSTRAINT ck_device_camera CHECK (camera_permission IN (\'UNKNOWN\',\'GRANTED\',\'DENIED\')), \n\tCONSTRAINT ck_device_phone CHECK (phone_permission IN (\'UNKNOWN\',\'GRANTED\',\'DENIED\')), \n\tCONSTRAINT ck_device_status CHECK (status IN (\'ACTIVE\',\'UNBOUND\',\'LOST\',\'DISABLED\')), \n\tCONSTRAINT ck_device_capabilities CHECK (jsonb_typeof(capabilities) = \'object\'), \n\tUNIQUE (device_id_hash), \n\tFOREIGN KEY(owner_user_id) REFERENCES "user" (id) ON DELETE RESTRICT\n)')
    op.execute('CREATE INDEX ix_device_owner_seen ON device_binding (owner_user_id, last_seen_at)')
    op.execute('CREATE TABLE family (\n\tid UUID NOT NULL, \n\tname VARCHAR(120) NOT NULL, \n\tcreated_by_user_id UUID NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'ACTIVE\' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_family_status CHECK (status IN (\'ACTIVE\',\'SUSPENDED\',\'DELETED\')), \n\tCONSTRAINT ck_family_name CHECK (length(name) > 0), \n\tFOREIGN KEY(created_by_user_id) REFERENCES "user" (id) ON DELETE RESTRICT\n)')
    op.execute('CREATE TABLE audit_log (\n\tid UUID NOT NULL, \n\tactor_user_id UUID, \n\tfamily_id UUID, \n\taction VARCHAR(64) NOT NULL, \n\ttarget_type VARCHAR(48) NOT NULL, \n\ttarget_id UUID, \n\treason VARCHAR(240), \n\trequest_id VARCHAR(96), \n\tresult VARCHAR(16) DEFAULT \'SUCCEEDED\' NOT NULL, \n\tmetadata_redacted JSONB DEFAULT \'{}\' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_audit_result CHECK (result IN (\'SUCCEEDED\',\'FAILED\',\'DENIED\')), \n\tCONSTRAINT ck_audit_metadata CHECK (jsonb_typeof(metadata_redacted) = \'object\'), \n\tFOREIGN KEY(actor_user_id) REFERENCES "user" (id) ON DELETE SET NULL, \n\tFOREIGN KEY(family_id) REFERENCES family (id) ON DELETE SET NULL\n)')
    op.execute('CREATE INDEX ix_audit_actor_created ON audit_log (actor_user_id, created_at)')
    op.execute('CREATE TABLE device_session (\n\tid UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tdevice_binding_id UUID, \n\trefresh_token_hash CHAR(64) NOT NULL, \n\tissued_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tlogout_reason VARCHAR(32), \n\tlast_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tip_hash CHAR(64), \n\tuser_agent_hash CHAR(64), \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_session_expiry CHECK (expires_at > issued_at), \n\tFOREIGN KEY(user_id) REFERENCES "user" (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(device_binding_id) REFERENCES device_binding (id) ON DELETE SET NULL, \n\tUNIQUE (refresh_token_hash)\n)')
    op.execute('CREATE TABLE family_invitation (\n\tid UUID NOT NULL, \n\tfamily_id UUID NOT NULL, \n\tcreated_by_user_id UUID NOT NULL, \n\ttoken_hash CHAR(64) NOT NULL, \n\ttarget_role VARCHAR(32) NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tmax_usage INTEGER DEFAULT \'1\' NOT NULL, \n\tused_count INTEGER DEFAULT \'0\' NOT NULL, \n\tused_at TIMESTAMP WITH TIME ZONE, \n\tstatus VARCHAR(16) DEFAULT \'ACTIVE\' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_invitation_role CHECK (target_role IN (\'ELDER\',\'CHILD\',\'CAREGIVER\',\'EMERGENCY_CONTACT\')), \n\tCONSTRAINT ck_invitation_status CHECK (status IN (\'ACTIVE\',\'USED\',\'REVOKED\',\'EXPIRED\')), \n\tCONSTRAINT ck_invitation_expiry CHECK (expires_at > created_at), \n\tCONSTRAINT ck_invitation_usage CHECK (max_usage > 0 AND used_count >= 0 AND used_count <= max_usage), \n\tFOREIGN KEY(family_id) REFERENCES family (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(created_by_user_id) REFERENCES "user" (id) ON DELETE RESTRICT, \n\tUNIQUE (token_hash)\n)')
    op.execute('CREATE TABLE family_member (\n\tid UUID NOT NULL, \n\tfamily_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\trole VARCHAR(32) NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'PENDING\' NOT NULL, \n\tpermission_codes JSONB DEFAULT \'{}\' NOT NULL, \n\tinvited_by_user_id UUID, \n\tjoined_at TIMESTAMP WITH TIME ZONE, \n\tleft_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_member_role CHECK (role IN (\'ELDER\',\'CHILD\',\'CAREGIVER\',\'EMERGENCY_CONTACT\')), \n\tCONSTRAINT ck_member_status CHECK (status IN (\'PENDING\',\'ACTIVE\',\'REVOKED\',\'LEFT\')), \n\tCONSTRAINT ck_member_permissions CHECK (jsonb_typeof(permission_codes) = \'object\'), \n\tFOREIGN KEY(family_id) REFERENCES family (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(user_id) REFERENCES "user" (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(invited_by_user_id) REFERENCES "user" (id) ON DELETE SET NULL\n)')
    op.execute('CREATE INDEX ix_member_family_status ON family_member (family_id, status)')
    op.execute("CREATE UNIQUE INDEX uq_member_current ON family_member (family_id, user_id) WHERE status IN ('PENDING','ACTIVE')")
    op.execute('CREATE TABLE consent (\n\tid UUID NOT NULL, \n\tfamily_id UUID NOT NULL, \n\tsubject_user_id UUID NOT NULL, \n\tgrantor_user_id UUID NOT NULL, \n\tgrantee_user_id UUID NOT NULL, \n\tscope VARCHAR(40) NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'GRANTED\' NOT NULL, \n\tversion INTEGER DEFAULT \'1\' NOT NULL, \n\tsource VARCHAR(24) DEFAULT \'SETTINGS\' NOT NULL, \n\tgranted_at TIMESTAMP WITH TIME ZONE, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\texpires_at TIMESTAMP WITH TIME ZONE, \n\treplaced_by_id UUID, \n\taudit_log_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_consent_scope CHECK (scope IN (\'VOICE\',\'PORTRAIT\',\'FAMILY_MEMORY\',\'HEALTH_MEDICATION\',\'CONVERSATION_SUMMARY\',\'CAMERA_PROXIMITY\',\'NOTIFICATION_TO_FAMILY\')), \n\tCONSTRAINT ck_consent_status CHECK (status IN (\'GRANTED\',\'REVOKED\',\'EXPIRED\')), \n\tCONSTRAINT ck_consent_source CHECK (source IN (\'ONBOARDING\',\'SETTINGS\',\'IMPORT\')), \n\tCONSTRAINT ck_consent_version CHECK (version > 0), \n\tCONSTRAINT ck_consent_granted CHECK (status <> \'GRANTED\' OR granted_at IS NOT NULL), \n\tCONSTRAINT ck_consent_revoked CHECK (status <> \'REVOKED\' OR revoked_at IS NOT NULL), \n\tFOREIGN KEY(family_id) REFERENCES family (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(subject_user_id) REFERENCES "user" (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(grantor_user_id) REFERENCES "user" (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(grantee_user_id) REFERENCES "user" (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(replaced_by_id) REFERENCES consent (id) ON DELETE SET NULL, \n\tFOREIGN KEY(audit_log_id) REFERENCES audit_log (id) ON DELETE SET NULL\n)')
    op.execute("CREATE INDEX ix_consent_granted ON consent (family_id, subject_user_id, grantee_user_id, scope) WHERE status = 'GRANTED'")


def downgrade():
    connection = op.get_bind()
    connection.execute(text('LOCK TABLE "consent", "family_member", "family_invitation", "device_session", "audit_log", "family", "device_binding", "user" IN ACCESS EXCLUSIVE MODE'))
    for table in ['consent', 'family_member', 'family_invitation', 'device_session', 'audit_log', 'family', 'device_binding', 'user']:
        if connection.execute(text(f'SELECT EXISTS (SELECT 1 FROM "{table}" LIMIT 1)')).scalar():
            raise RuntimeError("Downgrade requires an empty disposable database; use a forward fix for populated data")
    op.drop_table('consent')
    op.drop_table('family_member')
    op.drop_table('family_invitation')
    op.drop_table('device_session')
    op.drop_table('audit_log')
    op.drop_table('family')
    op.drop_table('device_binding')
    op.drop_table('user')
